// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {store} from '../models';

export function GetDbOptions():Promise<number>;

export function GetFibers():Promise<Array<store.Fiber>|Error>;

export function Weave(arg1:Array<number>):Promise<Error>;
