// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetDbOptions() {
  return window['go']['main']['App']['GetDbOptions']();
}

export function GetFibers() {
  return window['go']['main']['App']['GetFibers']();
}

export function Weave(arg1) {
  return window['go']['main']['App']['Weave'](arg1);
}
